
export const UI_STRINGS = {
  en: {
    appName: "TransLearn Studio",
    home: "Home",
    studio: "Studio",
    chat: "Assistant",
    settings: "Settings",
    profile: "Profile",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    username: "Username",
    password: "Password",
    confirmPassword: "Confirm Password",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    authError: "Invalid email or password",
    passMismatch: "Passwords do not match",
    emailExists: "Email already registered",
    newProject: "New Project",
    recentProjects: "My Creations",
    language: "Language",
    theme: "Theme",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    fontSize: "Font Size",
    support: "Support",
    contactUs: "Contact Support",
    name: "Name",
    email: "Email",
    message: "Your Message",
    send: "Send Message",
    back: "Back",
    save: "Save Changes",
    supportSuccess: "Message sent! We will reply within 48 hours.",
    selectLang: "Select Language",
    placeholder: "Ask your smart assistant...",
    changeAvatar: "Change Photo"
  },
  ar: {
    appName: "TransLearn Studio",
    home: "الرئيسية",
    studio: "الاستوديو",
    chat: "المساعد",
    settings: "الإعدادات",
    profile: "الملف الشخصي",
    login: "تسجيل الدخول",
    signup: "إنشاء حساب",
    logout: "تسجيل الخروج",
    username: "اسم المستخدم",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    noAccount: "ليس لديك حساب؟",
    haveAccount: "لديك حساب بالفعل؟",
    authError: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    passMismatch: "كلمات المرور غير متطابقة",
    emailExists: "البريد الإلكتروني مسجل مسبقاً",
    newProject: "مشروع جديد",
    recentProjects: "إبداعاتي",
    language: "اللغة",
    theme: "المظهر",
    darkMode: "الوضع الداكن",
    lightMode: "الوضع الفاتح",
    fontSize: "حجم الخط",
    support: "الدعم",
    contactUs: "تواصل مع الدعم",
    name: "الاسم",
    email: "البريد الإلكتروني",
    message: "رسالتك",
    send: "إرسال الرسالة",
    back: "الرجوع",
    save: "حفظ التغييرات",
    supportSuccess: "تم إرسال رسالتك! سيتم الرد خلال 48 ساعة.",
    selectLang: "اختر لغة الواجهة",
    placeholder: "اسأل مساعدك الذكي...",
    changeAvatar: "تغيير الصورة"
  },
  fr: {
    appName: "TransLearn Studio",
    home: "Accueil",
    studio: "Studio",
    chat: "Assistant",
    settings: "Paramètres",
    profile: "Profil",
    login: "Connexion",
    signup: "S'inscrire",
    logout: "Déconnexion",
    username: "Nom d'utilisateur",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    noAccount: "Pas de compte ?",
    haveAccount: "Déjà un compte ?",
    authError: "Email ou mot de passe invalide",
    passMismatch: "Les mots de passe ne correspondent pas",
    emailExists: "Email déjà enregistré",
    newProject: "Nouveau Projet",
    recentProjects: "Mes Créations",
    language: "Langue",
    theme: "Thème",
    darkMode: "Mode Sombre",
    lightMode: "Mode Clair",
    fontSize: "Taille du Texte",
    support: "Support",
    contactUs: "Contacter le Support",
    name: "Nom",
    email: "Email",
    message: "Votre Message",
    send: "Envoyer",
    back: "Retour",
    save: "Enregistrer",
    supportSuccess: "Message envoyé ! Réponse sous 48 heures.",
    selectLang: "Choisir la Langue",
    placeholder: "Posez votre question...",
    changeAvatar: "Changer la photo"
  }
};

export const LANGUAGES = [
  { code: 'ar', label: 'العربية', flag: '🇸🇦', dir: 'rtl' },
  { code: 'en', label: 'English', flag: '🇺🇸', dir: 'ltr' },
  { code: 'fr', label: 'Français', flag: '🇫🇷', dir: 'ltr' },
];
